export type CaseInfo = {
    id: string,
    title: string,
    description: string,
    creationDate?: Date,
    updateDate?: Date,
    deadline?: Date,
    status?: string,
    statusStep?: number,
    resident?: string,
    caretaker?: string,
    landlord?: string,
    imageUrl?: string,
    documents?: string[],
}
